"""init_models

Revision ID: 3b7c5caa4267
Revises: 
Create Date: 2023-03-05 20:04:20.884001

"""
import sqlalchemy as sa
from alembic import op

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = "3b7c5caa4267"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", CustomUUID, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=True)
    op.create_table(
        "employee",
        sa.Column("id", CustomUUID, nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("team_id", CustomUUID, nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_id"), "employee", ["id"], unique=False)
    op.create_table(
        "balance",
        sa.Column("id", CustomUUID, nullable=False),
        sa.Column("employee_id", CustomUUID, nullable=False),
        sa.Column("balance", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_balance_id"), "balance", ["id"], unique=False)
    op.create_table(
        "vacation",
        sa.Column("id", CustomUUID, nullable=False),
        sa.Column("employee_id", CustomUUID, nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column(
            "type", sa.Enum("UNPAID", "PAID", name="vacationtype"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacation_id"), "vacation", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacation_id"), table_name="vacation")
    op.drop_table("vacation")
    op.drop_index(op.f("ix_balance_id"), table_name="balance")
    op.drop_table("balance")
    op.drop_index(op.f("ix_employee_id"), table_name="employee")
    op.drop_table("employee")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
