"""create_team_table

Revision ID: c782c730870f
Revises: 27bf2aa3b8c7
Create Date: 2023-03-04 20:04:09.604307

"""
import sqlalchemy as sa
from alembic import op

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = "c782c730870f"
down_revision = "27bf2aa3b8c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", CustomUUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=True)
    op.add_column("employee", sa.Column("team_id", CustomUUID(), nullable=True))
    op.create_foreign_key(None, "employee", "team", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employee", type_="foreignkey")
    op.drop_column("employee", "team_id")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
